services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    mem_limit: 4g
    volumes:
      - ./qdrant_data:/qdrant/storage